// Generated by CoffeeScript 1.7.1
(function() {
  var CONFIG, DEBUG, URI, doReload, _ref;

  URI = Object.Uri.parse(('' + ((_ref = this.window) != null ? _ref.location : void 0)) || "");

  DEBUG = Object.DEBUG = true || URI.params.debug;

  CONFIG = {
    ID: "grodno.co",
    TITLE: "Grodno",
    VERSION: "1.5.2",
    COPYRIGHT: "2013, Grodno.Co",
    SOURCES: "0AqQx4KOOt8TGdEZWZHpBdXAtNlVSMUFMOXppQ3ZuMkE",
    GAT: "UA-37246628-1",
    GOOGLE_SHEETS_URI: "https://script.google.com/macros/s/AKfycbx1AsNPawV5QDldh0obaSRkSzaYT1ZA3mbQK40_WFMPDvUjT5cl/exec?doc=",
    GOOGLE_API_KEY: "AIzaSyAGenobWLKI-F6MWzrHIXmviwJww43n2EM"
  };

  Object.entity.create({
    id: 'app:webclient.Application',
    title: CONFIG.TITLE,
    plugins: [
      "remote:HttpService", "script:ScriptService", "settings:Settings", {
        id: "entity:EntityLoader"
      }, {
        id: "html:HtmlLoader",
        storage: Object.DEBUG ? null : window.localStorage
      }, {
        id: "db:IndexedDatabase",
        syncUriExpression: "'script://script.google.com/macros/s/AKfycbx1AsNPawV5QDldh0obaSRkSzaYT1ZA3mbQK40_WFMPDvUjT5cl/exec?doc=0AqQx4KOOt8TGdEZWZHpBdXAtNlVSMUFMOXppQ3ZuMkE&jsonp=callback&ts='+<@lastSynchedTimestampOnce>",
        version: 5,
        scheme: ['meta', 'links', 'enums', 'error']
      }, {
        id: "gsheet:Cache",
        storage: window.localStorage,
        uriPattern: 'script://script.google.com/macros/s/AKfycbx1AsNPawV5QDldh0obaSRkSzaYT1ZA3mbQK40_WFMPDvUjT5cl/exec?doc={{host}}&sheet={{path}}&jsonp=callback&version={{version}}'
      }, {
        id: "blogger:Cache",
        storage: window.sessionStorage,
        uriPattern: "script://www.googleapis.com/blogger/v3/blogs/{{host}}/posts?key=" + CONFIG.GOOGLE_API_KEY + "&jsonp=callback&_ssl=true&version={{version}}",
        cacheSerializer: function(data) {
          var s;
          if ((s = data != null ? data.items : void 0) && s.length) {
            return JSON.stringify(s);
          } else {
            return null;
          }
        }
      }
    ]
  });

  doReload = function() {
    var i, ls, o, _i, _len;
    ls = window.localStorage;
    for (i = _i = 0, _len = ls.length; _i < _len; i = ++_i) {
      o = ls[i];
      ls.removeItem(ls.key(i));
    }
    return ls;
  };

}).call(this);
