export default {
    shto: 'shto',
    pisha: 'shriftuet',
    josc: 'e',
    ugho: 'jugh',
    nelga: 'xaram',
    kalia: 'bliz',
    xocj: 'xoq',
    kab: 'qtob',
    jak: 'kaj',
    jasqe: 'esqe',
    tiaper: 'doper',
    tolki: 'adno',
    bolsh: 'vencej',
    amalj: 'badaj',
    isqu : 'shukaju',
    oqenj: 'bardzo',
    kotoraja: 'shto',
}