export default {
    shto: 'qto',
    pisha: 'pishet',
    josc: 'e',
    ugho: 'jugh',
    kalia: 'bliz',
    xocj: 'xoq',
    paslia: 'potym',
    kab: 'qtob',
    jak: 'kaj',
    jasqe: 'esqe',
    ciaper: 'doper',
    toljki: 'ano',
    boljsh: 'vencej',
    amalj: 'badaj',
}