export default {
    shto: 'qto',
    pisha: 'pishet',
    josc: 'e',
    ugho: 'jugh',
    nelga: 'xaram',
    kalia: 'bliz',
    xocj: 'xoq',
    paslia: 'potym',
    kab: 'qtob',
    jak: 'kaj',
    jasqe: 'esqe',
    tiaper: 'doper',
    tolki: 'adno',
    bolsh: 'vencej',
    amalj: 'badaj',
}