// Generated by CoffeeScript 1.8.0
(function() {
  Object.entity.define({
    id: "lexiomated.Plugin",
    properties: ['requires:Requires'],
    methods: function(_super) {
      return {
        perform: function(ev) {}
      };
    }
  });

}).call(this);
